version: '3.6'

services:
  validator:
    container_name: ${NODE_NAME:-validator5}
    image: hyperledger/besu:${BESU_VERSION:-latest}
    environment:
      - LOG4J_CONFIGURATION_FILE=/config/log-config.xml
      - NODE_NAME=${NODE_NAME:-validator5}
    restart: "on-failure"
    volumes:
      - ./config:/config
      - ./nodes/${NODE_NAME:-validator5}:/opt/besu/keys
      - ./logs/besu:/tmp/besu
    ports:
      - ${RPC_HTTP_PORT:-8545}:8545
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu \
        --data-path=/opt/besu/data \
        --config-file=/config/config.toml \
        --genesis-file=/config/genesis.json \
        --static-nodes-file=/config/static-nodes.json \
        --node-private-key-file=/opt/besu/keys/key \
        --p2p-host=$$(hostname -i) \
        --Xdns-enabled=true \
        --min-gas-price=0 \
        --rpc-http-api=ADMIN,DEBUG,TRACE,TXPOOL,WEB3,ETH,NET,PERM,IBFT \
        --rpc-ws-api=ADMIN,DEBUG,TRACE,TXPOOL,WEB3,ETH,NET,PERM,IBFT ;
