version: '3.6'

x-node:
  &node
  restart: "on-failure"
  image: hyperledger/besu:${BESU_VERSION:-latest}
  entrypoint:
    - /bin/bash
    - -c
    - |
      /opt/besu/bin/besu \
      --data-path=/opt/besu/data \
      --config-file=/config/config.toml \
      --genesis-file=/config/genesis.json \
      --node-private-key-file=/opt/besu/keys/key \
      --p2p-host=$$(hostname -i) \
      --Xdns-enabled=true \
      --min-gas-price=0 \
      --rpc-http-api=ADMIN,DEBUG,TRACE,TXPOOL,WEB3,ETH,NET,PERM,IBFT \
      --rpc-ws-api=ADMIN,DEBUG,TRACE,TXPOOL,WEB3,ETH,NET,PERM,IBFT \
      --bootnodes=enode://${BOOTNODE}@validator.cas-ll.net:30303 ;

services:
  validator5:
    <<: *node
    container_name: validator5
    environment:
      - LOG4J_CONFIGURATION_FILE=/config/log-config.xml
      - NODE_NAME=validator5
    volumes:
      - ./config:/config
      - ./nodes/validator5:/opt/besu/keys
      - ./logs/besu:/tmp/besu
    ports:
      - 35303:30303
      - 35545:8545
      - 35546:8546

  validator6:
    <<: *node
    container_name: validator6
    environment:
      - LOG4J_CONFIGURATION_FILE=/config/log-config.xml
      - NODE_NAME=validator6
    volumes:
      - ./config:/config
      - ./nodes/validator6:/opt/besu/keys
      - ./logs/besu:/tmp/besu
    depends_on:
      - validator5
    ports:
      - 36303:30303
      - 36545:8545
      - 36546:8546

